urls.py
from django.conf.urls.defaults import *

from greetme.views import index, add_greets, remove_greets, set_default_lang, deauth

from django.views.i18n import set_language

from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
                       (r'^$', index),
                       (r'^greetme/$', index),
                       (r'^greetme/add/$', add_greets),
                       (r'^greetme/remove/$',remove_greets), 
                       (r'^greetme/options/$', set_default_lang),
                       (r'^greetme/deauth/$', deauth),
                       
                       
                       (r'^i18n/set_lang/$', set_language),                       

                       
                       
                       #(r'^greetme/site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),


    # Example:
    # (r'^greetme/', include('greetme.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     (r'^greetme/admin/', include(admin.site.urls)),
)

greetme/models.py
from django.db import models
from djangofb.models import FacebookUser


class Language(models.Model):
    id = models.CharField(max_length=4, primary_key=True)
    name = models.CharField(max_length=20)
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        ordering = ['name']

class Greeting(models.Model):
    GENDER_CHOICES = (
        (u'M', u'Male'),
        (u'F', u'Female'),
    )
    gender = models.CharField(max_length=2, null=True, blank=True, choices=GENDER_CHOICES)
    lang = models.ForeignKey(Language)
     # Define the user optional when we want to create default greetings
    users = models.ManyToManyField(FacebookUser, null=True, blank=True)
    greeting = models.CharField(max_length=512)
    default = models.BooleanField()
    
    
    def __unicode__(self):
        return self.greeting
    
    
class DefaultLanguage(models.Model):
    user = models.ForeignKey(FacebookUser, primary_key=True)
    lang = models.ForeignKey(Language)
    def __unicode__(self):
        return str(self.user.uid) +' - '+ str(self.lang.name)
        
    
class ExcludedFriend(models.Model):
    user = models.ForeignKey(FacebookUser)
    friend_id = models.CharField(max_length=50, null=False, blank=False)
    
    def __unicode__(self):
        return str(self.user.uid) +' -> '+ str(self.friend_id)
    

templates/add_greets.html
{% extends "base-logged.html" %}
{% load i18n %}

{% block title %}{% trans "Greet Me - Add greeting" %}{% endblock %}


{% block body %}

  <p>
  {% blocktrans with user.name as name %}Add your greeting sentence {{name}}!!!{% endblocktrans %}
  </p>

  <p>{% trans "Put @first_name or @last_name so the application will replace them with first and last name of your friend." %}</p>
  <p>{% blocktrans %}For example: "Happy birthday @first_name!!!"
    It will be rendered as "Happy birthday David!!!"{% endblocktrans %}
  </p>
  <!--<p>To make more realistic sentences you can reduce the name of your friend.</p>-->
  <!--<p>For example: "Happy birthday @first_name3"-->
    <!--It will be rendered as "Happy birthday Jos!!!"-->
  <!--</p>-->
  {% if form.errors %}
  <p style="color: red;">
  {% blocktrans count form.errors|length as err %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}
  </p>
  {% endif %}
  <form action="" method="post">{% csrf_token %}
  
    <div class="field{% if form.lang.errors %} errors{% endif %}">
      {% if form.lang.errors %}
      <ul>
        {% for error in form.lang.errors %}
        <li><strong>{{ error }}</strong></li>
        {% endfor %}
      </ul>
      {% endif %}
      <label for="id_lang">{% trans "Language:" %}</label>
      {{ form.lang }}
    </div>
    
    <div class="field{% if form.lang.errors %} errors{% endif %}">
      {% if form.gender.errors %}
      <ul>
        {% for error in form.gender.errors %}
        <li><strong>{{ error }}</strong></li>
        {% endfor %}
      </ul>
      {% endif %}
      <label for="id_gender">{% trans "Gender:" %}</label>
      {{ form.gender }}
    </div>
    
    <div class="field{% if form.greeting.errors %} errors{% endif %}">
      {% if form.greeting.errors %}
      <ul>
        {% for error in form.greeting.errors %}
        <li><strong>{{ error }}</strong></li>
        {% endfor %}
      </ul>
      {% endif %}
      <label for="id_greeting">{% trans "Greeting:" %}</label>
      {{ form.greeting }}
    </div>
  
    <!--{{ form.as_table }}-->
    <input type="submit" value="{% trans 'Save' %}"/>
    <input type="button" value="{% trans 'Back' %}" onclick="location.href='/greetme/'" />
  </form>


{% endblock %}

templates/base-logged.html
{% extends "base.html" %}

{% block top-items %}
<ul>
    <li><a href="/greetme/" title="Home">Home</a></li> 
    <li><a href="/greetme/options/" title="Options">Options</a></li> 
</ul>
{% endblock%}

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="P3P" content='CP="IDC DSP COR CURa ADMa OUR IND PHY ONL COM STA"'>
    <title>{% block title %}Greet Me{% endblock %}</title>
    <link rel="stylesheet" href="{{ STATIC_URL }}/css/base.css" type="text/css" media="screen"/>
    {% block head %}{% endblock %}
  </head>
  
  <body>
    <script>
      function handleSessionChange(response) {
        if (( {{user_id}} && !response.session) ||
            {{user_id}} != response.session.uid) {
          goHome();
        }
      }
      
      function goHome() {
        top.location = '{{canvas_url}}';
      }
    </script>
    
    <div id="fb-root"></div>
    
    <script>
      
      window.fbAsyncInit = function() {
        FB.init({
          appId  : '{{ FACEBOOK_APP }}',
          status : true, // check login status
          cookie : true, // enable cookies to allow the server to access the session
          xfbml  : true, // parse XFBML
          oauth  : true // enable OAuth2.0
        });
        FB.Canvas.scrollTo(0,0);
        {% block subscribe %} {% endblock %}
        FB.Canvas.setAutoResize(); //set size according to iframe content size
        FB.Event.subscribe('auth.sessionChange', handleSessionChange);
      
        // ensure we're always running on apps.facebook.com
        if (window == top) { goHome(); }
        FB.Event.subscribe('auth.login', function(response) {
          goHome();
          // Reload the entire page. Could also do an Ajax request and dynamically
          // update the already loaded page.
          //window.location.reload(true);
        });
      
      };
      
      
      (function(d){
         var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
         js = d.createElement('script'); js.id = id; js.async = true;
         js.src = "//connect.facebook.net/en_US/all.js";
         d.getElementsByTagName('head')[0].appendChild(js);
       }(document));
       
      <!--(function() {-->
      <!--var e = document.createElement('script');-->
      <!--e.type = 'text/javascript';-->
      <!--e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';-->
      <!--e.async = true;-->
      <!--document.getElementById('fb-root').appendChild(e);-->
      <!--}());-->
    </script>
    
    <div id="doc">
      <div id="top-wrapper"> 
        <div id="top">
          <ul id="current-language" class="sf-menu"> 
            <li class="current"> 
              <a id="language-selector"> 
                <span>&darr; Language</span> 
              </a> 
              <ul id="languages">
                <form name="lang_form" action="/i18n/set_lang/" method="post">
                  {% csrf_token %}
                  <input name="next" type="hidden" value="" />
                  <input name="language" type="hidden" value="" />
                  <li><a onclick="lang_form.language.value='en'; document.lang_form.submit();">
                    <span class="language-label">English</span> 
                  </a></li>
                  <li><a onclick="lang_form.language.value='it'; document.lang_form.submit();">
                    <span class="language-label">Italiano</span>
                  </a></li>
                  <li><a onclick="lang_form.language.value='es'; document.lang_form.submit();">
                    <span class="language-label">Español</span> 
                  </a></li> 
                  
                </form> 
              </ul>
            </li>
          </ul>
          {% block top-items %}{% endblock%}
        </div>
      </div>
      <div id="content">{% block body %}{% endblock %}</div>
      <br/>
    </div>

  </body>
  
</html>

templates/base_run.html
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">
  <head>
    <meta charset="utf-8">
    <title>
      {% block title %}Welcome{% endblock %} &mdash; Run with Friends
    </title>
    <meta name="description" content="Track and share your runs with friends.">
    <link type="text/css" rel="stylesheet" href="/awesome-buttons.css">
    <link type="text/css" rel="stylesheet" href="/main.css">
  </head>
  <body>
    <div id="doc">
      <div class="hd">
        {% if logged_in_user %}
          <div id="user-info">
            <div class="info">
              <a class="name" href="/user/{{ logged_in_user.user_id }}">
                {{ logged_in_user.name }}
              </a>
              <a class="logout" onclick="FB.logout()">Logout</a>
            </div>
            <img width="50" height="50" src="{{ logged_in_user.picture }}">
          </div>
        {% endif %}
        <a class="logo" href="/">Run with Friends</a>
      </div>

      {% if message %}
        <div class="message {{ message.type }}">{{ message.content|safe }}</div>
      {% endif %}

      <div class="bd">
        {% block body %}{% endblock %}
      </div><!-- .bd -->

      <div class="ft">
        This is an awesome running
        <span onclick="FB.api({ method: 'auth.revokeAuthorization' })">
          app
        </span>.
        <a class="rfloat" target="_new"
           href="http://github.com/facebook/runwithfriends">
          Source code available on Github.
        </a>
      </div>
    </div>

    <script src="/main.js"></script>
    <div id="fb-root"></div>
    <script>
      {# async loading of facebook js sdk #}
      window.fbAsyncInit = function() { facebookInit({{ js_conf|safe }}) };
      (function() {
        var e = document.createElement('script');
        e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
        document.getElementById('fb-root').appendChild(e);
      }());

      {# async loading of google analytics #}
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-19854556-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script');
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ga, s);
      })();
    </script>
  </body>
</html>

templates/index.html
{% extends "base-logged.html" %}

{% load i18n %}

{% block title %}{% trans "Greet Me - Home" %}{% endblock %}


{% block body %}

  <p>
    <img style="float:left;margin-right:10px" src="http://graph.facebook.com/{{ uid }}/picture"/>
    {% blocktrans %}Welcome {{ first_name }}!!!{% endblocktrans %}
  </p>

  <p>{% blocktrans %}This application is very simple!!!
  Just add your greeting sentences and the application automatically will give greetings at your friends!!
  That's all!!!{% endblocktrans %}
  </p>
  <p>{% blocktrans %}<b>Warning:</b> If you change your Facebook password remember to come back in this page of the GreetMe app (Just go to Facebook Homepage and click on the Phone application in the left side).
  In this way, GreetMe can update the new access token matched with the new password and send greetings to your friends. Otherwise, GreetMe couldn't work for you until you won't do that.{% endblocktrans %}
  </p>

  <form action="/greetme/remove/" method="POST">{% csrf_token %}

    <div class="listing clear">
      <table class="alws" width="100%" cellspacing="0" cellpadding="4" border="0">  
      
        <thead>
          <tr>
            <th width="10%">
              {% trans "Select" %}
              <!--<input type="checkbox" id="select_all" onClick="select.checked=yes" name="select_all"/>-->
            </th>
            <th width="10%">{% trans "Gender" %}</th>
            <th width="20%">{% trans "Language" %}</th>
            <th>{% trans "Greeting sentences" %}</th>
          </tr>
        </thead>
        <tbody>
      
          {% for greet in greets %}
          <tr class="odd" onmouseout="this.className='odd'" onmouseover="this.className='highlight'">
            <td><input type="checkbox" id="select" value="{{greet.id}}" name="select"/></td>
            <td>
              {% if greet.gender %}
                {{ greet.gender}}
              {% else %}
                G
              {% endif %}
            </td>
            <td>{{ greet.lang}}</td>
            <td>{{ greet.greeting}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    
    </div>
    
    <input type="button" name="add" value="{% trans 'Add greeting'%} " onclick="window.location='/greetme/add/'" />
    <input type="submit" name="remove" value="{% trans 'Remove selected greetings'%}"/>
  </form>

  
<!--<script type="text/javascript">-->

<!--var select=document.getElementById("select_all")-->

<!--select.onchange=function(){ //run some code when "onchange" event fires-->
 <!--document.getElementById("select").checked = this.checked-->
 <!--var chosenoption=this.options[this.selectedIndex] //this refers to "selectmenu"-->
 <!--if (chosenoption.value!="nothing"){-->
  <!--window.open(chosenoption.value, "", "") //open target site (based on option's value attr) in new window-->
 <!--}-->
<!--}-->

<!--</script>  -->
  

{% endblock %}

templates/options.html
{% extends "base-logged.html" %}

{% load i18n %}

{% block title %}{% trans "Greet Me - Options" %}{% endblock %}


{% block body %}


  
  {% if form.errors %}
  <p style="color: red;">
  {% blocktrans count form.errors|length as err %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}
  </p>
  {% endif %}
  
  <form action="" method="post">{% csrf_token %}
    <p>
      {% blocktrans %}Here you can set the default language used when doesn't exist a greeting sentence
      with the language of your friend:{% endblocktrans %}
    </p>
    <table>
    {{ form.as_table }}
    </table>
    <br/>
      <p>
        {% blocktrans %}Choose the friends whose will receive your automatic greetings.
        Uncheck somebody of them if you want to make manual greetings or if you just want that they don't receive greetings from you:{% endblocktrans %}
      </p>
    <table>
      {% for f in excluded_friends|dictsort:"name" %}
        {% if forloop.counter0|divisibleby:3 %}<tr>{% endif %}
          <td>
            <input type="checkbox" id="select" value="{{f.id}}" name="select"/>
            <img src="http://graph.facebook.com/{{f.id}}/picture"/>
            <br/>
            {{f.name}}
          </td>
        {% if forloop.counter|divisibleby:3 or forloop.last %}</tr>{% endif %}
      {% endfor %}
      {% for f in included_friends|dictsort:"name" %}
        {% if forloop.counter0|divisibleby:3 %}<tr>{% endif %}
          <td>
            <input type="checkbox" id="select" value="{{f.id}}" name="select" checked="checked"/>
            <img src="http://graph.facebook.com/{{f.id}}/picture"/>
            <br/>
            {{f.name}}
          </td>
        {% if forloop.counter|divisibleby:3 or forloop.last %}</tr>{% endif %}
      {% endfor %}
      
    </table>
    
    <input type="submit" value="{% trans 'Save' %}"/>
    <input type="button" value="{% trans 'Back' %}" onclick="location.href='/greetme/'" />
  </form>
{% endblock %}

templates/welcome.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}GreetMe Facebook Application{% endblock %}

{% block body %}
<div class="welcome">
  <h1>{% blocktrans %}Welcome to GreetMe Facebook Application{% endblocktrans %}</h1>
  <img class="promo" alt="Welcome to Greet Me" src="{{ STATIC_URL }}images/splash.jpg">
  <div class="info">
    <p>
      {% blocktrans %}This is a simple application that allow you to make greetings automatically
      to your friends for their birthday.{% endblocktrans %}
    </p>
    <p>
      {% blocktrans %}In order to appear like a realistic greeting in the wall of your friend, the name of the application
      is quite changed in Phone ;){% endblocktrans %}
    </p>
    <p>
      {% blocktrans %}In order to use GreetMe you must sign in with your Facebook account:{% endblocktrans %}
      <div id="login-flow">
        <fb:login-button perms="publish_stream,offline_access,friends_birthday" show-faces="true"></fb:login-button>
      </div>
    </p>
  </div>
</div>

{% endblock %}